### YamlMime:ManagedReference
items:
- uid: NuvTools.Security.AspNetCore.Configurations
  commentId: N:NuvTools.Security.AspNetCore.Configurations
  id: NuvTools.Security.AspNetCore.Configurations
  children:
  - NuvTools.Security.AspNetCore.Configurations.SecurityConfigurationSection
  - NuvTools.Security.AspNetCore.Configurations.ServiceCollectionExtensions
  langs:
  - csharp
  - vb
  name: NuvTools.Security.AspNetCore.Configurations
  nameWithType: NuvTools.Security.AspNetCore.Configurations
  fullName: NuvTools.Security.AspNetCore.Configurations
  type: Namespace
  assemblies:
  - NuvTools.Security.AspNetCore
references:
- uid: NuvTools.Security.AspNetCore.Configurations.SecurityConfigurationSection
  commentId: T:NuvTools.Security.AspNetCore.Configurations.SecurityConfigurationSection
  isExternal: true
  href: NuvTools.Security.AspNetCore.Configurations.SecurityConfigurationSection.html
  name: SecurityConfigurationSection
  nameWithType: SecurityConfigurationSection
  fullName: NuvTools.Security.AspNetCore.Configurations.SecurityConfigurationSection
- uid: NuvTools.Security.AspNetCore.Configurations.ServiceCollectionExtensions
  commentId: T:NuvTools.Security.AspNetCore.Configurations.ServiceCollectionExtensions
  isExternal: true
  href: NuvTools.Security.AspNetCore.Configurations.ServiceCollectionExtensions.html
  name: ServiceCollectionExtensions
  nameWithType: ServiceCollectionExtensions
  fullName: NuvTools.Security.AspNetCore.Configurations.ServiceCollectionExtensions
